"""
crews/tasks.py
Task templates for each agent. These use CrewAI's {placeholder} interpolation
so the Flow can pass in the structured JSON payloads collected during the
conversation. Kept as functions (not module-level Task objects) because each
Crew kickoff needs fresh Task instances bound to that run's inputs.
"""
from __future__ import annotations

from crewai import Task

from crews.agents import (
    financial_synthesizer_agent,
    grant_strategist_agent,
    statutory_compliance_agent,
)


def make_statutory_tasks(document_types: list[str]) -> list[Task]:
    validate_task = Task(
        description=(
            "Validate the company profile JSON at {company_profile_json} for "
            "ACRA-filing blockers (missing resident director, no shareholders, "
            "invalid paid-up capital, missing SSIC code). If issues are found, "
            "list them clearly instead of proceeding to render documents."
        ),
        expected_output="Either 'OK' or a bulleted list of specific issues to resolve with the user.",
        agent=statutory_compliance_agent,
    )
    render_task = Task(
        description=(
            "Only if the validation task returned OK: render the following "
            "ACRA documents from the same company profile JSON: "
            f"{', '.join(document_types)}. Call the render tool once per "
            "document type. Return the RenderedDocument JSON for each."
        ),
        expected_output="A JSON array of RenderedDocument objects, one per requested document type.",
        agent=statutory_compliance_agent,
        context=[validate_task],
    )
    return [validate_task, render_task]


def make_financial_task() -> Task:
    return Task(
        description=(
            "Using the assumptions provided in {financial_assumptions_json} "
            "(starting_monthly_revenue_sgd, monthly_revenue_growth_pct, "
            "cogs_pct_of_revenue, fixed_monthly_opex_sgd, starting_cash_sgd), "
            "generate the 3-year forecast via the forecast tool, then produce "
            "a one-paragraph plain-English summary via the summary tool. If "
            "any assumption looks implausible (e.g. >50% monthly growth "
            "sustained for 36 months), say so explicitly before proceeding."
        ),
        expected_output=(
            "The full FinancialForecast JSON followed by a short plain-English "
            "summary paragraph."
        ),
        agent=financial_synthesizer_agent,
    )


def make_grant_tasks(scheme: str) -> list[Task]:
    validate_task = Task(
        description=(
            f"Validate that {{narrative_sections_json}} contains all required "
            f"sections for the '{scheme}' scheme and that none are too thin. "
            "If sections are missing or thin, list exactly what's needed from "
            "the user instead of proceeding."
        ),
        expected_output="Either 'OK' or a specific list of missing/thin sections.",
        agent=grant_strategist_agent,
    )
    compile_task = Task(
        description=(
            "Only if narrative validation returned OK: compile the final grant "
            f"package for scheme '{scheme}' using {{company_profile_json}}, "
            "{financial_forecast_json} (already generated by the Financial "
            "Synthesizer — do not recompute), {headcount_plan_json}, "
            "{narrative_sections_json}, and {requested_amount_sgd}."
        ),
        expected_output="The full GrantPackage JSON including generated_document_path.",
        agent=grant_strategist_agent,
        context=[validate_task],
    )
    return [validate_task, compile_task]
