"""
crews/document/tasks.py
Prompt-text builders for the Document Team Lead and each document specialist.
These return plain strings for Agent.kickoff(...) calls — no crewai.Task or
Crew objects — because dispatch and sequencing are handled directly by
OrchestratorFlow (flows/orchestrator_flow.py), and each specialist is a
standalone Agent (crews/document/agents.py) invoked on its own, not
coordinated through a Crew.
"""
from __future__ import annotations

import json


def build_document_routing_prompt(sub_query: str, business_context: dict) -> str:
    return (
        "A business owner's question, already rephrased for the document team, is:\n"
        f'"{sub_query}"\n\n'
        f"Anything already known from earlier in the conversation (JSON): {json.dumps(business_context)}\n\n"
        "Decide which ONE document specialist should handle this:\n"
        '- "statutory": Singapore ACRA BizFile+ incorporation paperwork (Model '
        "Constitution, Form 45, Form 45B, First Board Resolution, RORC register). "
        "If this is the one, list which document type(s) were asked for in "
        "document_types.\n"
        '- "financial": a 3-year cash flow / P&L forecast, burn rate, and '
        "break-even estimate.\n"
        '- "grant": a Startup SG Founder or EDG grant package. If this is the '
        "one, set grant_scheme "
        '("startup_sg_founder" or "enterprise_development_grant") and '
        "requested_amount_sgd from whatever the owner has said (leave either "
        "null if not yet known — that's fine, don't guess).\n\n"
        "The company profile, financial assumptions, grant narrative, and "
        "headcount plan themselves are NOT something you need to gather or "
        "extract — each specialist already has its own reference data for "
        "this business and loads it directly. Your job is only to pick the "
        "specialist and, for statutory/grant, the request-specific choices "
        "above.\n\n"
        'If you can tell which specialist applies, set route_type to "dispatch". '
        "If you genuinely cannot tell even from the rephrased question, set "
        'route_type to "clarify" and ask exactly one specific question in '
        "clarifying_question."
    )


def build_statutory_render_prompt(document_types: list[str], company_profile_json: str) -> str:
    return (
        "The following CompanyProfile JSON has already been validated as "
        f"complete and ACRA-filing-ready:\n{company_profile_json}\n\n"
        "Render the following ACRA documents by calling the render tool once "
        f"per document type: {', '.join(document_types)}.\n"
        "Return the RenderedDocument JSON for each, followed by one "
        "plain-English sentence per document summarizing what was produced."
    )


def build_financial_prompt(financial_assumptions_json: str, computed_summary: str) -> str:
    return (
        "The 3-year cash flow / P&L forecast below has already been computed "
        "deterministically from the assumptions shown — you do not need to "
        "(and should not try to) recompute or restate the underlying numbers "
        "yourself; there is no tool to call here.\n\n"
        f"Assumptions JSON: {financial_assumptions_json}\n\n"
        f"Computed summary: {computed_summary}\n\n"
        "If any assumption looks implausible (e.g. >50% monthly growth "
        "sustained for 36 months), say so explicitly. Then write a rigorous "
        "one-paragraph plain-English summary of this forecast for a business "
        "owner, grounded only in the computed summary above."
    )


def build_grant_prompt(
    scheme: str,
    company_profile_json: str,
    financial_forecast_json: str,
    headcount_plan_json: str,
    narrative_sections_json: str,
    requested_amount_sgd: float,
) -> str:
    return (
        f"Compile the final grant package for scheme '{scheme}' by calling "
        "the compile tool with the data below. The narrative sections have "
        "already been validated as complete for this scheme; the financial "
        "forecast was already generated by the Financial Synthesizer — do "
        "not recompute it.\n\n"
        f"company_profile_json: {company_profile_json}\n"
        f"financial_forecast_json: {financial_forecast_json}\n"
        f"headcount_plan_json: {headcount_plan_json}\n"
        f"narrative_sections_json: {narrative_sections_json}\n"
        f"requested_amount_sgd: {requested_amount_sgd}\n\n"
        "Return the full GrantPackage JSON including generated_document_path."
    )
